### ISSUE TITLE
Image picker does not return a result when using CleanUI

### ISSUE THREAD

**Issue by ln-12** [knoggl/CleanUI#3]
I noticed that the image picker in my app stopped working after using your library. I can push the picker sheet, take a photo and select it, but after the sheet is closed, no callback is triggered. I setup a minimal example here: https://github.com/ln-12/cleanui_test

You will notice that the image is not added to the UI after selection. If you go to the project settings and remove CleanUI from the package dependencies, the photo selection works just fine. I also want to point out that I am not even using CleanUI in this minimal example. Just because of adding it as dependency, the workflow breaks. Do you have any idea why? 

Maybe overriding the delegate in [`viewDidLoad` for UINavigationControllerDelegate](https://github.com/knoggl/CleanUI/blob/70e3fe1baa471f2b430aecaab690c9fd327df2b4/Sources/CleanUI/Extensions/UIKit/UINavigationController.swift#L27) is a bad idea?

**Comment by juliangerhards** [comment]
Interesting. I haven't had this issue because we are using PHPickerViewController only. I will add an option to turn off the ``UINavigationControllerDelegate`` in the next days, this should fix it. Or maybe i set the default to OFF. We'll see.

> I also want to point out that I am not even using CleanUI in this minimal example. Just because of adding it as dependency, the workflow breaks.

Yes this is because CleanUI is designed to have a default full-width back gesture. But like I said, I will change the default behavior.

**Comment by ln-12** [comment]
Hey, thanks for your fast response. In my opinion it would be needed to turn the back gesture off when the view controller launches and turn it back on once it is finished. Looking forward to your solution!

**Comment by juliangerhards** [comment]
This should fix the issue https://github.com/knoggl/CleanUI/commit/074d88e9f8bbf3fd06862acb92e480232bd1f347
Made a new release with the fix [1.6.1](https://github.com/knoggl/CleanUI/releases/tag/1.6.1)

**Comment by ln-12** [comment]
Well, it fixes the original problem, but not having swipe to go back is a problem too. In my case both works when commenting out [the delegate](https://github.com/knoggl/CleanUI/blob/70e3fe1baa471f2b430aecaab690c9fd327df2b4/Sources/CleanUI/Extensions/UIKit/UINavigationController.swift#L27).

**Comment by juliangerhards** [comment]
You have swipe to go back with the default UINavigationBar, Just not with the CleanUI .navigationBar().
If you need the CleanUI.navigationBar() you have to import this package https://github.com/knoggl/iOSFullWidthBackGesture, which brings you back to the initial problem.

If you don't mind using the default "Apple" UINavigationBar just use the .toolbar modifier. Otherwise you have to come up with a different solution. 

If you comment out the delegate, the custom Push and PopTransition doesnt work anymore....

**Comment by ln-12** [comment]
Alright, thanks for the clarification! As I don't need custom transitions, I get everything I need without the delegate, but I totally see why this approach is not suitable here. I simply created a fork for my project and think that we can close this issue. Thanks again for you work!

**Comment by juliangerhards** [comment]
I just removed the delegate and replaced the [1.6.1 Release](https://github.com/knoggl/CleanUI/releases/tag/1.6.1). The UINavigationController delegate is now used inside the Knoggl-iOS app instead of CleanUI which solves all the problems.
